export const ADD_LIKES = "ADD_LIKES";
export const REMOVE_LIKES = "REMOVE_LIKES";
export const ADD_BLOCKS = "ADD_BLOCKS";
export const REMOVE_BLOCKS = "REMOVE_BLOCKS";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const GET_CAROUSEL_MOVIE = "GET_CAROUSEL_MOVIE";
export const GET_MOVIES_REQUEST = "GET_MOVIES_REQUEST";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";

