export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS';
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR';

export const GET_LIKES_REQUEST = 'GET_LIKES_REQUEST';
export const ADD_LIKES = 'ADD_LIKES';
